# Generated by Django 5.0.6 on 2024-06-07 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'verbose_name_plural': 'Thống kê'},
        ),
    ]
