# Generated by Django 5.0.6 on 2024-06-17 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('topic', models.CharField(choices=[('Giá vàng', 'Giá vàng'), ('Xăng dầu', 'Xăng dầu'), ('Tài chính', 'Tài chính'), ('Nông sản', 'Nông sản')], max_length=20)),
                ('author', models.CharField(max_length=100)),
                ('link_img', models.CharField(max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('info_extrac', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tin tức',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
            options={
                'verbose_name_plural': 'Lịch sử đọc tin',
            },
        ),
        migrations.CreateModel(
            name='NewsSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
            options={
                'verbose_name_plural': 'Quản lý Tag- Tin tức',
            },
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.news')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lưu tin tức',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('newss', models.ManyToManyField(through='news.NewsSearch', to='news.news')),
            ],
            options={
                'verbose_name_plural': 'Từ khoá tìm kiếm',
            },
        ),
        migrations.AddField(
            model_name='newssearch',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.search'),
        ),
        migrations.AddField(
            model_name='news',
            name='searchs',
            field=models.ManyToManyField(through='news.NewsSearch', to='news.search'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('newss', models.ManyToManyField(through='news.NewsTag', to='news.news')),
            ],
            options={
                'verbose_name_plural': 'Quản lý Tags',
            },
        ),
        migrations.AddField(
            model_name='newstag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.tag'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(through='news.NewsTag', to='news.tag'),
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='newssearch',
            unique_together={('news', 'search')},
        ),
        migrations.AlterUniqueTogether(
            name='newstag',
            unique_together={('news', 'tag')},
        ),
    ]
