# Generated by Django 4.0.1 on 2024-05-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='topic',
            field=models.CharField(choices=[('giá vàng', 'Giá vàng'), ('hàng hoá', 'Hàng hoá'), ('chứng khoán', 'Chứng khoán')], max_length=100),
        ),
    ]
