# Generated by Django 5.0.6 on 2024-06-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tinh chỉnh Tags thủ công'},
        ),
    ]
