# Generated by Django 4.0.1 on 2024-05-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_id_alter_news_time_alter_news_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='topic',
            field=models.CharField(choices=[('giá vàng', 'Giá vàng'), ('hàng hoá', 'Hàng hoá'), ('chứng khoán', 'Chứng khoán'), ('tài chính', 'Tài chính')], max_length=100),
        ),
    ]
