# Generated by Django 5.0.6 on 2024-06-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Quản lý tin tức'},
        ),
        migrations.AlterField(
            model_name='news',
            name='link_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
