# Generated by Django 5.0.6 on 2024-06-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_options_alter_news_link_img'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newstag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='newstag',
            name='relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='newstag',
            unique_together={('news', 'tag', 'relation')},
        ),
    ]
