# Generated by Django 5.0.6 on 2024-05-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='topic',
            field=models.CharField(choices=[('Giá vàng', 'Giá vàng'), ('Xăng dầu', 'Xăng dầu'), ('Tài chính', 'Tài chính'), ('Nông sản', 'Nông sản'), ('Thực phẩm', 'Thực phẩm')], max_length=100),
        ),
    ]
