# Generated by Django 5.0.6 on 2024-06-25 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newstag_unique_together_newstag_relation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_show', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Nguyên nhân',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='topic',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='KeyReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.reason')),
            ],
        ),
    ]
