# Generated by Django 5.0.6 on 2024-05-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_tag_newstag_usertag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTag',
        ),
    ]
