# Generated by Django 5.0.6 on 2024-06-25 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_keyreason_description_remove_reason_keyreason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(blank=True, max_length=100, null=True)),
                ('keyreasons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.keyreason')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
            options={
                'verbose_name_plural': 'Quản lý Tag- Tin tức',
                'unique_together': {('news', 'keyreasons', 'sentiment')},
            },
        ),
    ]
