# Generated by Django 5.0.6 on 2024-05-18 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_usertag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
