# Generated by Django 5.0.6 on 2024-06-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_newsreason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsreason',
            options={'verbose_name_plural': 'Quản lý Nguyên nhân- Tin tức'},
        ),
    ]
