# Generated by Django 5.0.6 on 2024-05-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_usertag_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(through='news.NewsTag', to='news.tag'),
        ),
    ]
