# Generated by Django 5.0.6 on 2024-06-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_newsreason_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeyReason',
            new_name='KeyReason10',
        ),
    ]
