# Generated by Django 5.0.6 on 2024-05-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_news_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newstag',
            unique_together={('news', 'tag')},
        ),
    ]
