# Generated by Django 5.0.6 on 2024-06-26 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_rename_keyreason_keyreason10'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newsreason',
            unique_together={('news', 'sentiment')},
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.reason')),
            ],
            options={
                'verbose_name_plural': 'Từ khoá nguyên nhân',
            },
        ),
    ]
