# Generated by Django 5.0.6 on 2024-06-26 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_newsreason_unique_together_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeyReason10',
            new_name='KeyReason',
        ),
        migrations.AlterField(
            model_name='newsreason',
            name='keyreasons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.key'),
        ),
    ]
