# Generated by Django 5.0.6 on 2024-05-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_newstag_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='newss',
            field=models.ManyToManyField(through='news.NewsTag', to='news.news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='topic',
            field=models.CharField(choices=[('Giá vàng', 'Giá vàng'), ('Xăng dầu', 'Xăng dầu'), ('Tài chính', 'Tài chính'), ('Nông sản', 'Nông sản')], max_length=100),
        ),
    ]
