# Generated by Django 5.0.6 on 2024-06-26 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_rename_keyreason10_keyreason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsreason',
            name='keyreasons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.keyreason'),
        ),
        migrations.DeleteModel(
            name='Key',
        ),
    ]
