# Generated by Django 5.0.6 on 2024-06-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_newsreason_keyreasons_delete_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newsreason',
            unique_together=set(),
        ),
    ]
