# Generated by Django 5.0.6 on 2024-07-08 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_newsreason_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='newss',
        ),
        migrations.RemoveField(
            model_name='news',
            name='searchs',
        ),
        migrations.DeleteModel(
            name='NewsSearch',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
