# Generated by Django 5.0.6 on 2024-06-07 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_newssearch_search_newssearch_search_news_searchs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Lịch sử đọc tin'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Tin tức'},
        ),
        migrations.AlterModelOptions(
            name='save',
            options={'verbose_name_plural': 'Lưu tin tức'},
        ),
    ]
