# Generated by Django 5.0.6 on 2024-06-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Quản lý chủ đề',
            },
        ),
        migrations.CreateModel(
            name='Crawls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(choices=[('VNexpress', 'VNexpress'), ('Vietnam Biz', 'Vietnam Biz'), ('Cafef', 'Cafef'), ('VnEconomy', 'VnEconomy'), ('Mobiagri', 'Mobiagri'), ('Thanh niên', 'Thanh niên')], max_length=20)),
                ('url', models.URLField()),
                ('is_collected', models.BooleanField(default=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl.topic')),
            ],
            options={
                'verbose_name_plural': 'Thiết lập nguồn tin',
            },
        ),
    ]
