# Generated by Django 5.0.6 on 2024-06-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
    ]
