# Generated by Django 5.0.6 on 2024-06-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crawl',
            options={'verbose_name_plural': 'Thu thập tin tức'},
        ),
        migrations.AlterField(
            model_name='crawl',
            name='topic',
            field=models.CharField(choices=[('Giá vàng', 'Giá vàng'), ('Xăng dầu', 'Xăng dầu'), ('Tài chính', 'Tài chính'), ('Nông sản', 'Nông sản')], max_length=100),
        ),
    ]
