# Generated by Django 5.0.6 on 2024-06-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_rename_authors_crawl_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
