# Generated by Django 5.0.6 on 2024-06-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0003_topic_is_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Thiết lập nhóm Tag ',
            },
        ),
        migrations.AlterModelOptions(
            name='crawl',
            options={'verbose_name_plural': 'Thiết lập thu thập tin'},
        ),
    ]
