# Generated by Django 5.0.6 on 2024-06-19 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0004_grouptag_alter_crawl_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grouptag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl.grouptag')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl.topic')),
            ],
            options={
                'verbose_name_plural': 'Quản lý chủ đề-nhóm Tag',
                'unique_together': {('topic', 'grouptag')},
            },
        ),
    ]
