# Generated by Django 5.0.6 on 2024-06-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0005_topictag'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(through='crawl.TopicTag', to='crawl.grouptag'),
        ),
    ]
