# Generated by Django 5.0.6 on 2024-07-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0009_alter_crawl_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawl',
            name='author',
            field=models.CharField(choices=[('VNexpress', 'VNexpress'), ('Vietnam Biz', 'Vietnam Biz'), ('Cafef', 'Cafef'), ('VnEconomy', 'VnEconomy'), ('Mobiagri', 'Mobiagri'), ('Thanh niên', 'Thanh niên'), ('Tapchicongthuong', 'Tạp chí công thương'), ('dantri', 'Dân trí')], max_length=20),
        ),
    ]
